# Gathering Data

In [1]:
!wget -O moviedataset.zip https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/moviedataset.zip
print('unziping ...')
!unzip -o -j moviedataset.zip

--2020-08-26 10:15:05--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/moviedataset.zip
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 160301210 (153M) [application/zip]
Saving to: ‘moviedataset.zip’

moviedataset.zip    100%[===================>] 152.88M  40.5MB/s    in 3.8s

2020-08-26 10:15:09 (40.3 MB/s) - ‘moviedataset.zip’ saved [160301210/160301210]

unziping ...
Archive:  moviedataset.zip
  inflating: links.csv
  inflating: movies.csv
  inflating: ratings.csv
  inflating: README.txt
  inflating: tags.csv

# Imports and read data

In [2]:
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
movies_df = pd.read_csv('movies.csv')

In [4]:
movies_df.head()

   movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

# Preprocessing

Fixing title column by extracting and putting all years in new column

In [5]:
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)

#Removing the parentheses
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)

#Removing the years from the 'title' column
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')

#Applying the strip function to get rid of any ending whitespace characters that may have appeared
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df.head()

   movieId  ...  year
0        1  ...  1995
1        2  ...  1995
2        3  ...  1995
3        4  ...  1995
4        5  ...  1995

[5 rows x 4 columns]

Fixing genre column

In [6]:
#Every genre is separated by a | so we simply have to call the split function on |
movies_df['genres'] = movies_df.genres.str.split('|')
movies_df.head()

   movieId  ...  year
0        1  ...  1995
1        2  ...  1995
2        3  ...  1995
3        4  ...  1995
4        5  ...  1995

[5 rows x 4 columns]

One Hot Encoding

In [7]:
#Copying the movie dataframe into a new one since we won't need to use the genre information in our first case.
moviesWithGenres_df = movies_df.copy()

#For every row in the dataframe, iterate through the list of genres and place a 1 into the corresponding column
for index, row in movies_df.iterrows():
    for genre in row['genres']:
        moviesWithGenres_df.at[index, genre] = 1
#Filling in the NaN values with 0 to show that a movie doesn't have that column's genre
moviesWithGenres_df = moviesWithGenres_df.fillna(0)
moviesWithGenres_df.head()

   movieId                        title  ... Film-Noir (no genres listed)
0        1                    Toy Story  ...       0.0                0.0
1        2                      Jumanji  ...       0.0                0.0
2        3             Grumpier Old Men  ...       0.0                0.0
3        4            Waiting to Exhale  ...       0.0                0.0
4        5  Father of the Bride Part II  ...       0.0                0.0

[5 rows x 24 columns]

# Take user input

In [8]:
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

**Add movieId to input user**  
By first filtering out the rows that contain the input movie's title and then merging this subset with the input dataframe. We also drop unnecessary columns for the input to save memory space.

In [9]:
#Filtering out the movies by title
inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]

In [10]:
inputId.head()

      movieId  ...  year
0           1  ...  1995
1           2  ...  1995
293       296  ...  1994
1246     1274  ...  1988
1885     1968  ...  1985

[5 rows x 4 columns]

In [11]:
#Then merging it so we can get the movieId. It's implicitly merging it by title.
inputMovies = pd.merge(inputId, inputMovies)

In [12]:
#Dropping information we won't use from the input dataframe
inputMovies = inputMovies.drop('genres', 1).drop('year', 1)
inputMovies

   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0

If a movie you added in above isn't here, then it might not be in the original dataframe or it might spelled differently, please check capitalisation.

# Make User profile

We'll only need the actual genre table, so let's clean this up a bit by resetting the index and dropping the movieId, title, genres and year columns.

In [13]:
#Filtering out the movies from the input
userMovies = moviesWithGenres_df[moviesWithGenres_df['movieId'].isin(inputMovies['movieId'].tolist())]
userMovies

      movieId                title  ... Film-Noir (no genres listed)
0           1            Toy Story  ...       0.0                0.0
1           2              Jumanji  ...       0.0                0.0
293       296         Pulp Fiction  ...       0.0                0.0
1246     1274                Akira  ...       0.0                0.0
1885     1968  Breakfast Club, The  ...       0.0                0.0

[5 rows x 24 columns]

In [14]:
#Resetting the index to avoid future issues
userMovies = userMovies.reset_index(drop=True)
#Dropping unnecessary issues due to save memory and to avoid issues
userGenreTable = userMovies.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)
userGenreTable

   Adventure  Animation  Children  ...  Western  Film-Noir  (no genres listed)
0        1.0        1.0       1.0  ...      0.0        0.0                 0.0
1        1.0        0.0       1.0  ...      0.0        0.0                 0.0
2        0.0        0.0       0.0  ...      0.0        0.0                 0.0
3        1.0        1.0       0.0  ...      0.0        0.0                 0.0
4        0.0        0.0       0.0  ...      0.0        0.0                 0.0

[5 rows x 20 columns]

Now we're ready to start learning the input's preferences!

To do this, we're going to turn each genre into weights. We can do this by using the input's reviews and multiplying them into the input's genre table and then summing up the resulting table by column. This operation is actually a dot product between a matrix and a vector, so we can simply accomplish by calling Pandas's "dot" function.

In [15]:
inputMovies['rating']

0    3.5
1    2.0
2    5.0
3    4.5
4    5.0
Name: rating, dtype: float64

In [16]:
#Dot produt to get weights
userProfile = userGenreTable.transpose().dot(inputMovies['rating'])
#The user profile
userProfile

Adventure             10.0
Animation              8.0
Children               5.5
Comedy                13.5
Fantasy                5.5
Romance                0.0
Drama                 10.0
Action                 4.5
Crime                  5.0
Thriller               5.0
Horror                 0.0
Mystery                0.0
Sci-Fi                 4.5
IMAX                   0.0
Documentary            0.0
War                    0.0
Musical                0.0
Western                0.0
Film-Noir              0.0
(no genres listed)     0.0
dtype: float64

Now, we have the weights for every of the user's preferences. This is known as the User Profile. Using this, we can recommend movies that satisfy the user's preferences.

# Find Recommendation table

Let's start by extracting the genre table from the original dataframe:

In [17]:
#Now let's get the genres of every movie in our original dataframe
genreTable = moviesWithGenres_df.set_index(moviesWithGenres_df['movieId'])
#And drop the unnecessary information
genreTable = genreTable.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)
genreTable.head()

         Adventure  Animation  Children  ...  Western  Film-Noir  (no genres listed)
movieId                                  ...
1              1.0        1.0       1.0  ...      0.0        0.0                 0.0
2              1.0        0.0       1.0  ...      0.0        0.0                 0.0
3              0.0        0.0       0.0  ...      0.0        0.0                 0.0
4              0.0        0.0       0.0  ...      0.0        0.0                 0.0
5              0.0        0.0       0.0  ...      0.0        0.0                 0.0

[5 rows x 20 columns]

In [18]:
genreTable.shape

(34208, 20)

With the input's profile and the complete list of movies and their genres in hand, we're going to take the weighted average of every movie based on the input profile and recommend the top twenty movies that most satisfy it.

In [19]:
#Multiply the genres by the weights and then take the weighted average
recommendationTable_df = ((genreTable*userProfile).sum(axis=1))/(userProfile.sum())
recommendationTable_df.head()

movieId
1    0.594406
2    0.293706
3    0.188811
4    0.328671
5    0.188811
dtype: float64

In [20]:
#Sort our recommendations in descending order
recommendationTable_df = recommendationTable_df.sort_values(ascending=False)
#Just a peek at the values
recommendationTable_df.head()

movieId
5018      0.748252
26093     0.734266
27344     0.720280
148775    0.685315
6902      0.678322
dtype: float64

In [21]:
#The final recommendation table
movies_df.loc[movies_df['movieId'].isin(recommendationTable_df.head(20).keys())]

       movieId  ...  year
664        673  ...  1996
1824      1907  ...  1998
2902      2987  ...  1988
4923      5018  ...  1991
6793      6902  ...  2002
8605     26093  ...  1962
8783     26340  ...  1976
9296     27344  ...  1999
9825     32031  ...  2005
11716    51632  ...  2003
11751    51939  ...  2007
13250    64645  ...  1968
16055    81132  ...  2010
18312    91335  ...  2009
22778   108540  ...  2012
22881   108932  ...  2014
25218   117646  ...  2000
26442   122787  ...  1959
32854   146305  ...  2000
33509   148775  ...  2009

[20 rows x 4 columns]

# Advantages and Disadvantages of Content-Based Filtering

##### Advantages
* Learns user's preferences
* Highly personalized for the user

##### Disadvantages
* Doesn't take into account what others think of the item, so low quality item recommendations might happen
* Extracting data is not always intuitive
* Determining what characteristics of the item the user dislikes or likes is not always obvious